In [1]:
import numpy as np

In [2]:
a=[1,2,3,4]
b=[5,6,7,8]

In [3]:
output=[]
for i,j in zip(a,b):
    output.append(i+j)

In [4]:
print(output)

[6, 8, 10, 12]


In [5]:
g= list(range(1000000))

In [6]:
%timeit sum(g)

45 ms ± 694 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
h= np.array(g)

In [8]:
type(h)

numpy.ndarray

In [9]:
%timeit np.sum(h)

397 µs ± 8.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [25]:
#all ops in numpy unless specified are point to point

a=np.array(a)
b=[5,6,7,8]
b=np.array(b)
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [28]:
print(a//b)
print(a/b)

[0 0 0 0]
[0.2        0.33333333 0.42857143 0.5       ]


In [29]:
a+b

array([ 6,  8, 10, 12])

In [30]:
a-b

array([-4, -4, -4, -4])

In [31]:
a+20

array([21, 22, 23, 24])

In [32]:
a.dtype

dtype('int32')

In [33]:
m=np.sin(a)
n=np.log(a)
o=np.exp(a)
print(m)
print(n)
print(o)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [34]:
a.ndim

1

In [35]:
x=(10)
type(x)

int

In [36]:
x=10,
type(x)

tuple

In [37]:
 np.log

<ufunc 'log'>

In [38]:
np.sum

<function numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [39]:
print(a)
a[0]=-1
print(a)

[1 2 3 4]
[-1  2  3  4]


In [41]:
a[3]=10.12
a

array([-1,  2,  3, 10])

In [42]:
a.fill(4)
a

array([4, 4, 4, 4])

In [43]:
a.fill(4.8)
a

array([4, 4, 4, 4])

In [44]:
a=np.array([1,2,3,4])
print(a.dtype)

a=np.array([1,2,3,4,10.2])

int32


In [45]:
x=[10,11,12]
y=[20,21,22]
a=np.array([x,y])
a

array([[10, 11, 12],
       [20, 21, 22]])

In [46]:
a.dtype

dtype('int32')

In [47]:
a.ndim

2

In [48]:
a.shape

(2, 3)

In [49]:
print(a)
a.T

[[10 11 12]
 [20 21 22]]


array([[10, 20],
       [11, 21],
       [12, 22]])

In [50]:
a[1:3]

array([[20, 21, 22]])

In [51]:
a[2:3]

array([], shape=(0, 3), dtype=int32)

In [52]:
a[2:3]

array([], shape=(0, 3), dtype=int32)

In [53]:
a[1:2]

array([[20, 21, 22]])

In [54]:
a=np.arange(0,25).reshape(5,5)

In [55]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [56]:
print(a[::4,::4])

[[ 0  4]
 [20 24]]


In [57]:
a=np.array([1,2,3,4,5])
b=3
c=a+b
c

array([4, 5, 6, 7, 8])